# Generated by Django 3.2.5 on 2022-06-09 12:01

import Store.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(height_field=500, upload_to=Store.models.get_file_path)),
                ('brief_description', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('clearance_sale', models.BooleanField(default=False, help_text='0=default, 1=Clearance')),
                ('new_arrival', models.BooleanField(default=False, help_text='0=default, 1=New Arrival')),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_keywords', models.CharField(max_length=150)),
                ('meta_descripion', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.category')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Store.size')),
            ],
        ),
    ]
