# Generated by Django 4.0.5 on 2022-06-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='meta_descripion',
            new_name='meta_description',
        ),
    ]
