# Generated by Django 4.0.5 on 2022-06-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='name',
        ),
    ]
