# Generated by Django 3.2.5 on 2022-06-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_rename_slug_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='Size_category',
        ),
    ]
