# Generated by Django 3.2.5 on 2022-06-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_alter_product_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size_category',
            new_name='Size_categori',
        ),
    ]
