# Generated by Django 3.2.5 on 2022-06-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_rename_size_category_size_categori'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size_categori',
            new_name='Size_categorie',
        ),
    ]
