# Generated by Django 3.2.5 on 2022-06-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_rename_size_categori_size_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='description',
            field=models.CharField(max_length=30),
        ),
    ]
