# Generated by Django 3.2.5 on 2022-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_auto_20220621_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size_categorie',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
