# Generated by Django 3.2.5 on 2022-06-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_alter_size_categorie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Store.size_categorie'),
        ),
    ]
