# Generated by Django 3.2.5 on 2022-06-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0023_alter_size_size_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='viewed_on_homepage',
        ),
    ]
