# Generated by Django 3.2.5 on 2022-06-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0025_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='buying_price',
        ),
    ]
