# Generated by Django 3.2.5 on 2022-06-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0027_auto_20220623_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Clearance',
            field=models.BooleanField(default=False, help_text='0=default, 1=Clearance'),
        ),
    ]
