# Generated by Django 3.2.5 on 2022-06-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0034_rename_slug_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
