# Generated by Django 3.2.5 on 2022-07-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0035_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='size_category',
        ),
        migrations.AddField(
            model_name='size',
            name='petite',
            field=models.BooleanField(default=False, help_text='0=default, 1=Petite'),
        ),
        migrations.AddField(
            model_name='size',
            name='plus',
            field=models.BooleanField(default=False, help_text='0=default, 1=PlusSize'),
        ),
    ]
