# Generated by Django 3.2.5 on 2022-07-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0036_auto_20220707_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='plus',
            new_name='PlusSize',
        ),
    ]
