# Generated by Django 3.2.5 on 2022-07-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0038_alter_product_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size_categorie',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
