# Generated by Django 3.2.5 on 2022-07-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0039_auto_20220707_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='slug',
        ),
    ]
