# Generated by Django 3.2.5 on 2022-07-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0040_rename_name_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='name',
        ),
    ]
