# Generated by Django 3.2.5 on 2022-07-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0042_auto_20220707_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
