# Generated by Django 3.2.5 on 2022-07-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0045_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
