# Generated by Django 3.2.5 on 2022-07-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0046_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, default=False, max_length=150, null=True),
        ),
    ]
