# Generated by Django 3.2.5 on 2022-07-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0047_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=False, max_length=150, null=True),
        ),
    ]
